RM = rm -f
AR = ar rcu
DC = gdc
DFLAGS = -Wall -Wextra -pedantic -Isrc
GDB = -funittest -fdebug -ggdb3
#GDB = -O3
LIB = 

VPATH = src:src/tvm:src/tvm/vm:src/tvm/compiler

OBJS = lfds611.o main.o all.o ast.o codegen.o parser.o printer.o scanner.o sema.o tokens.o allocator.o bytecode.o interpreter.o objects.o scheduler.o utils.o

TARGET = tvm

all : $(TARGET)

$(TARGET) : $(OBJS) $(LIB)
	$(DC) $^ $(DLDLIBS) -o$@

%.o : %.d
	$(DC) $(DFLAGS) $(GDB) $< -c

clean:
	$(RM) $(TARGET)
	$(RM) $(OBJS)

